FROM rust:1.85-slim AS builder

WORKDIR /usr/src/app
COPY . .

RUN cargo build --release --bin client

FROM debian:bookworm-slim
WORKDIR /usr/local/bin

RUN apt-get update && apt-get install -y \
    iputils-ping \
    netcat-openbsd \
    iproute2 \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/app/target/release/client .

CMD ["./client"]
