FROM rust:1.85-slim AS builder

WORKDIR /usr/src/app
COPY . .

# CHANGE THIS: Build the client, not the hub
RUN cargo build --release --bin client

# Etapa 2: Ejecución
FROM debian:bookworm-slim
WORKDIR /usr/local/bin

RUN apt-get update && apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/*

# This will now find the 'client' binary created above
COPY --from=builder /usr/src/app/target/release/client .

CMD ["./client"]