
FROM rust:1.85-slim AS builder

WORKDIR /usr/src/app
COPY . .

RUN cargo build --release --bin hub

FROM debian:bookworm-slim
WORKDIR /usr/local/bin

RUN apt-get update && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/local/bin/output

COPY --from=builder /usr/src/app/target/release/hub* .

EXPOSE 7878

CMD ["./hub"]